env: MountainCarContinuous-v0
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 10
nbTest: 1
freqVerbose: 10
fromFile: null
nbEpisodes: 1000
activation: !!python/name:torch.tanh ''
layers:
- 200

lr: 0.001
batchsize: 100
discount: 0.999
capacity: 2000
epsilon : 1
Q_hat_update_step: 50
eta: 0.01
epsilon_min : 0.01
prior: True
