env: gridworld-v0
map: gridworldPlans/plan0.txt
rewards:
  0: -0.001
  3: 1
  4: 1
  5: -1
  6: -1
seed: 5
featExtractor: !!python/name:__main__.MapFromDumpExtractor2 ''
freqSave: 1000
freqTest: 10
nbTest: 1
freqVerbose: 100
fromFile: null
nbEpisodes: 1000000
activation: !!python/name:torch.tanh ''
layers:
- 200

lr: 0.001
batchsize: 100
discount: 0.999
capacity: 2000
epsilon : 1
Q_hat_update_step: 50