Q_hat_update_step: 50
activation: !!python/name:None.tanh ''
batchsize: 100
capacity: 2000
discount: 0.999
env: CartPole-v1
epsilon: 1
featExtractor: !!python/name:utils.NothingToDo ''
freqSave: 1000
freqTest: 10
freqVerbose: 100
fromFile: null
layers:
- 200
lr: 0.001
nbEpisodes: 1000000
nbTest: 1
seed: 5
